import type { Metadata } from "next";
import "./globals.css";
import Layout from "./_components/Layout";
import Header from "./_components/header";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Smart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className="w-full bg-main-bg text-darktext">

      <div className="">
      </div>
        <Layout>
        <Toaster />


          <Header/>
         

        {children}

        </Layout>
        </body>
    </html>
  );
}
