import type { Metadata } from "next";
import "./globals.css";
import Layout from "./_components/Layout";
import Header from "./_components/header";
import Home from "./page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full bg-main-bg text-darktext">

        
        <Layout>

          <Header/>
        {children}

        </Layout>
        </body>
    </html>
  );
}
